#%RAML 1.0 DataType
type: object
properties:
  quantity:
    type: number
    example: 1
    required: true
  remaining_amount:
    type: number
    required: true
    example: 2
  date:
    type: date-only
    required: true
    example: 2024-04-24
  name_load:
    type: string
    required: true
    example: "ivan"
  product_id:
    type: string
    required: true
    example: "76ty80"
  purchase_price:
    type: number
    required: true
    example: 10
  sale_price:
    type: number
    required: true
    example: 12
  name_product:
    type: string
    required: true
    example: "jabon zote"