#%RAML 1.0 DataType
type: object
properties:
  "product_type":
    type: string
    required: true
    example: "abarrotes"
  product:
    type: object
    properties:  
      "product_id":
        type: string
        required: true
        example: "A5A1V466V4Sadv65af4gv65"
      "name_product":
        type: string
        required: true
        example: "escoba"
      "net_content":
        type: string
        required: true
        example: "N/A"
      "date_of_expiry":
        type: string
        required: true
        example: "N/A"
      "amount":
        type: number
        required: true
        example: 50
      "purchase_price":
        type: number
        required: true
        example: 10
      "total_quantity":
        type: number
        required: true
        example: 500