#%RAML 1.0
title: tn-store-movil-api-svc
types:
  register_admin: !include /data_type/user_register.raml
  user-login: !include /data_type/user_login.raml
  recover_password: !include /data_type/post_recover_password.raml
  new_password: !include /data_type/patch_new_password.raml
  post_product: !include data_type/product.raml
  load: !include data_type/load.raml
  inventory: !include /data_type/post_inventory.raml
  
traits:
  secure: !include /trait/secure.raml
  getInventory: !include /trait/get_inventory.raml
/users:
  is: [secure]
  post:
    description: este servicio regitra al administrador de la compania
    body:
      application/json:
        type: register_admin
    responses:
      500:
        description: Bad response from authorization server, or WSDL SOAP Fault error
      201:
        body:
            application/json:
                example: !include /example/responses/post_register.json
  /login:
    is: [secure]
    post:
      description: este servicio permite logear el usuario
      body:
        application/json:
          type: user-login
      responses:
        401:
          description: Unauthorized or invalid client application credentials
        500:
          description: Bad response from authorization server, or WSDL SOAP Fault error
        200:
          body:
              application/json:
                  example: !include /example/responses/post_login.json
  /recoverPassword:
    is: [secure]
    post:
      description: Estre servicio no ayuda a recuperar la contraseña guadada en la base de datos
      body:
        application/json:
          type: recover_password
      responses:
        200:
          body:
            application/json:
              example: !include /example/responses/recoverPassword.json
  /new_password:
    is: [secure]
    patch:
      queryParameters:
        email:
          type: string
          required: true
      description: Este servicio acualizara la contraseña
      body:
        application/json:
          type: new_password
      responses:
        200:
          body:
            application/json:
              example: !include /example/patch_new_password.json
/products:
  is: [secure]
  post:
    description: Este servicio permite crear el objeto producto
    body:
        application/json:
            type: post_product
    responses:
        201:
          body:
            application/json:
              example: !include example/responses/post_Product.json
  get:
    description: Este servicio trae el objeto product de la BD
    responses:
      200:
        body:
          application/json:
            example: !include example/responses/get_Product.json
/loads:
    is: [secure]
    post:
      description: Este servicio permite crear el objeto load
      body:
        application/json:
          type: load
      responses:
        201:
          body:
            application/json:
              example: !include example/responses/post_load.json
    get:
      queryParameters:
        name_load:
          type: string
          required: false
      description: Este servicio trae todas registrados en Db
      responses:
        200:
          body:
            application/json:
              example: !include example/responses/get_load.json
/inventory:
  post:
    description: This service adds products to inventory
    body:
      application/json:
        type: inventory
    responses:
      201:
        body:
          application/json:
            example: !include /example/responses/post_inventory.json
  get:
    is: [getInventory]      
    description: This service calls what is requested 
    responses:
      200:
        body:
          application/json:
            example: !include /example/responses/get_inventory.json    