#%RAML 1.0 Trait
description: 
queryParameters:
  product: 
    type: string
    required: false
    example: "zapato1"
  amount:
    type: number
    required: false
    example: 50
  purchase_price:
    type: number
    required: false
    example: 10
  total_quantity:
    type: number
    required: false
    example: 500
  product_type:
    type: string
    required: true
    example: "abarratos"