#%RAML 1.0 Trait
description: 
queryParameters:
  product_type:
    type: string
    required: true
    example: "abarrotes"
  product: 
    type: string
    required: false
    example: "zapato1"
  amount:
    type: number
    required: false
    example: 50